/-
Copyright (c) 2017 Microsoft Corporation. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.

wasm/compat: the `Mathlib.Tactic` umbrella, compiled under its real module
name (see wasm/compat/README.md). Upstream (mathlib4 de3a9cf,
Mathlib/Tactic.lean) is a `module` file that `public import`s 356
`Mathlib.Tactic.*` modules; the essential Mathlib pack this build ships
EXCLUDES the umbrella itself and 112 of its leaves. This file imports the
244 leaves the pack does contain (exactly the pack's `Mathlib.Tactic.*`
modules, every one of which upstream's umbrella imports) plus the two
compat leaves `Mathlib.Tactic.Have` and `Mathlib.Tactic.Cases`, so a
game's unmodified `import Mathlib.Tactic` (NumberTheoryGame,
lean4game-logic) resolves. Generated from the pack module list; no
Mathlib code is copied here.
-/
import Mathlib.Tactic.Abel
import Mathlib.Tactic.AdaptationNote
import Mathlib.Tactic.Algebraize
import Mathlib.Tactic.ApplyAt
import Mathlib.Tactic.ApplyCongr
import Mathlib.Tactic.ApplyFun
import Mathlib.Tactic.ApplyWith
import Mathlib.Tactic.Attr.Core
import Mathlib.Tactic.Attr.Register
import Mathlib.Tactic.Basic
import Mathlib.Tactic.Bound
import Mathlib.Tactic.Bound.Attribute
import Mathlib.Tactic.Bound.Init
import Mathlib.Tactic.ByCases
import Mathlib.Tactic.ByContra
import Mathlib.Tactic.CancelDenoms.Core
import Mathlib.Tactic.CasesM
import Mathlib.Tactic.Check
import Mathlib.Tactic.Choose
import Mathlib.Tactic.ClearExcept
import Mathlib.Tactic.ClearExclamation
import Mathlib.Tactic.Clear_
import Mathlib.Tactic.ClickSuggestions
import Mathlib.Tactic.ClickSuggestions.Apply
import Mathlib.Tactic.ClickSuggestions.ApplyAt
import Mathlib.Tactic.ClickSuggestions.FindPremises
import Mathlib.Tactic.ClickSuggestions.GRewrite
import Mathlib.Tactic.ClickSuggestions.Rewrite
import Mathlib.Tactic.ClickSuggestions.SectionState
import Mathlib.Tactic.ClickSuggestions.TryPremises
import Mathlib.Tactic.ClickSuggestions.Unfold
import Mathlib.Tactic.ClickSuggestions.Util
import Mathlib.Tactic.Coe
import Mathlib.Tactic.Common
import Mathlib.Tactic.ComputeDegree
import Mathlib.Tactic.CongrExclamation
import Mathlib.Tactic.CongrM
import Mathlib.Tactic.Constructor
import Mathlib.Tactic.Continuity
import Mathlib.Tactic.Continuity.Init
import Mathlib.Tactic.ContinuousFunctionalCalculus
import Mathlib.Tactic.Contrapose
import Mathlib.Tactic.Conv
import Mathlib.Tactic.Convert
import Mathlib.Tactic.Core
import Mathlib.Tactic.CrossRefAttribute
import Mathlib.Tactic.DSimpPercent
import Mathlib.Tactic.DeclarationNames
import Mathlib.Tactic.DefEqAbuse
import Mathlib.Tactic.DefEqTransformations
import Mathlib.Tactic.DepRewrite
import Mathlib.Tactic.DeprecateTo
import Mathlib.Tactic.DeriveFintype
import Mathlib.Tactic.Eqns
import Mathlib.Tactic.ErwQuestion
import Mathlib.Tactic.ExistsI
import Mathlib.Tactic.ExtendDoc
import Mathlib.Tactic.ExtractGoal
import Mathlib.Tactic.FBinop
import Mathlib.Tactic.FailIfNoProgress
import Mathlib.Tactic.FastInstance
import Mathlib.Tactic.Field
import Mathlib.Tactic.FieldSimp
import Mathlib.Tactic.FieldSimp.Attr
import Mathlib.Tactic.FieldSimp.Discharger
import Mathlib.Tactic.FieldSimp.Lemmas
import Mathlib.Tactic.FinCases
import Mathlib.Tactic.Find
import Mathlib.Tactic.Finiteness
import Mathlib.Tactic.Finiteness.Attr
import Mathlib.Tactic.FunProp
import Mathlib.Tactic.FunProp.Attr
import Mathlib.Tactic.FunProp.Core
import Mathlib.Tactic.FunProp.Decl
import Mathlib.Tactic.FunProp.Elab
import Mathlib.Tactic.FunProp.FunctionData
import Mathlib.Tactic.FunProp.Mor
import Mathlib.Tactic.FunProp.Theorems
import Mathlib.Tactic.FunProp.ToBatteries
import Mathlib.Tactic.FunProp.Types
import Mathlib.Tactic.GCongr
import Mathlib.Tactic.GCongr.Core
import Mathlib.Tactic.GCongr.CoreAttrs
import Mathlib.Tactic.GCongr.ForwardAttr
import Mathlib.Tactic.GRewrite
import Mathlib.Tactic.GRewrite.Core
import Mathlib.Tactic.GRewrite.Elab
import Mathlib.Tactic.GrindAttrs
import Mathlib.Tactic.Group
import Mathlib.Tactic.GuardGoalNums
import Mathlib.Tactic.GuardHypNums
import Mathlib.Tactic.HaveI
import Mathlib.Tactic.HigherOrder
import Mathlib.Tactic.Hint
import Mathlib.Tactic.InferParam
import Mathlib.Tactic.Inhabit
import Mathlib.Tactic.IntervalCases
import Mathlib.Tactic.IrreducibleDef
import Mathlib.Tactic.Lemma
import Mathlib.Tactic.Lift
import Mathlib.Tactic.Linarith
import Mathlib.Tactic.Linarith.Datatypes
import Mathlib.Tactic.Linarith.Frontend
import Mathlib.Tactic.Linarith.Lemmas
import Mathlib.Tactic.Linarith.Oracle.SimplexAlgorithm
import Mathlib.Tactic.Linarith.Oracle.SimplexAlgorithm.Datatypes
import Mathlib.Tactic.Linarith.Oracle.SimplexAlgorithm.Gauss
import Mathlib.Tactic.Linarith.Oracle.SimplexAlgorithm.PositiveVector
import Mathlib.Tactic.Linarith.Oracle.SimplexAlgorithm.SimplexAlgorithm
import Mathlib.Tactic.Linarith.Parsing
import Mathlib.Tactic.Linarith.Preprocessing
import Mathlib.Tactic.Linarith.Verification
import Mathlib.Tactic.LinearCombination
import Mathlib.Tactic.LinearCombination.Lemmas
import Mathlib.Tactic.Linter
import Mathlib.Tactic.Linter.AuxLemma
import Mathlib.Tactic.Linter.DeprecatedSyntaxLinter
import Mathlib.Tactic.Linter.DirectoryDependency
import Mathlib.Tactic.Linter.DocPrime
import Mathlib.Tactic.Linter.DocString
import Mathlib.Tactic.Linter.EmptyLine
import Mathlib.Tactic.Linter.FlexibleLinter
import Mathlib.Tactic.Linter.GlobalAttributeIn
import Mathlib.Tactic.Linter.HashCommandLinter
import Mathlib.Tactic.Linter.HaveLetLinter
import Mathlib.Tactic.Linter.Header
import Mathlib.Tactic.Linter.Lint
import Mathlib.Tactic.Linter.MinImports
import Mathlib.Tactic.Linter.Multigoal
import Mathlib.Tactic.Linter.OldObtain
import Mathlib.Tactic.Linter.OverlappingInstances
import Mathlib.Tactic.Linter.PPRoundtrip
import Mathlib.Tactic.Linter.PrivateModule
import Mathlib.Tactic.Linter.Style
import Mathlib.Tactic.Linter.TacticDocumentation
import Mathlib.Tactic.Linter.UnusedInstancesInType
import Mathlib.Tactic.Linter.UnusedTactic
import Mathlib.Tactic.Linter.UnusedTacticExtension
import Mathlib.Tactic.Linter.UpstreamableDecl
import Mathlib.Tactic.Linter.Whitespace
import Mathlib.Tactic.MinImports
import Mathlib.Tactic.MkIffOfInductiveProp
import Mathlib.Tactic.Module
import Mathlib.Tactic.Monotonicity.Attr
import Mathlib.Tactic.NoncommRing
import Mathlib.Tactic.Nontriviality
import Mathlib.Tactic.Nontriviality.Core
import Mathlib.Tactic.NormNum
import Mathlib.Tactic.NormNum.Abs
import Mathlib.Tactic.NormNum.Basic
import Mathlib.Tactic.NormNum.BigOperators
import Mathlib.Tactic.NormNum.Core
import Mathlib.Tactic.NormNum.DivMod
import Mathlib.Tactic.NormNum.Eq
import Mathlib.Tactic.NormNum.GCD
import Mathlib.Tactic.NormNum.Ineq
import Mathlib.Tactic.NormNum.Inv
import Mathlib.Tactic.NormNum.NatFactorial
import Mathlib.Tactic.NormNum.OfScientific
import Mathlib.Tactic.NormNum.Pow
import Mathlib.Tactic.NormNum.Result
import Mathlib.Tactic.NthRewrite
import Mathlib.Tactic.Observe
import Mathlib.Tactic.OfNat
import Mathlib.Tactic.Order
import Mathlib.Tactic.Order.CollectFacts
import Mathlib.Tactic.Order.Graph.Basic
import Mathlib.Tactic.Order.Graph.Tarjan
import Mathlib.Tactic.Order.Preprocessing
import Mathlib.Tactic.Order.ToInt
import Mathlib.Tactic.PPWithUniv
import Mathlib.Tactic.Peel
import Mathlib.Tactic.Polynomial.Core
import Mathlib.Tactic.Positivity
import Mathlib.Tactic.Positivity.Basic
import Mathlib.Tactic.Positivity.Core
import Mathlib.Tactic.Positivity.Finset
import Mathlib.Tactic.ProxyType
import Mathlib.Tactic.Push
import Mathlib.Tactic.Push.Attr
import Mathlib.Tactic.Qify
import Mathlib.Tactic.RSuffices
import Mathlib.Tactic.Recover
import Mathlib.Tactic.Relation.Rfl
import Mathlib.Tactic.Rename
import Mathlib.Tactic.RenameBVar
import Mathlib.Tactic.Rify
import Mathlib.Tactic.Ring
import Mathlib.Tactic.Ring.Basic
import Mathlib.Tactic.Ring.Common
import Mathlib.Tactic.Ring.Compare
import Mathlib.Tactic.Ring.PNat
import Mathlib.Tactic.Ring.RingNF
import Mathlib.Tactic.Says
import Mathlib.Tactic.ScopedNS
import Mathlib.Tactic.Set
import Mathlib.Tactic.SetLike
import Mathlib.Tactic.SetNotationForOrder
import Mathlib.Tactic.SimpIntro
import Mathlib.Tactic.SimpRw
import Mathlib.Tactic.Simproc.ExistsAndEq
import Mathlib.Tactic.Simps.Basic
import Mathlib.Tactic.Simps.NotationClass
import Mathlib.Tactic.SplitIfs
import Mathlib.Tactic.Spread
import Mathlib.Tactic.Subsingleton
import Mathlib.Tactic.Substs
import Mathlib.Tactic.SuccessIfFailWithMsg
import Mathlib.Tactic.SudoSetOption
import Mathlib.Tactic.SuppressCompilation
import Mathlib.Tactic.SwapVar
import Mathlib.Tactic.TFAE
import Mathlib.Tactic.TacticAnalysis
import Mathlib.Tactic.TacticAnalysis.Declarations
import Mathlib.Tactic.Tauto
import Mathlib.Tactic.TautoSet
import Mathlib.Tactic.TermCongr
import Mathlib.Tactic.ToAdditive
import Mathlib.Tactic.ToDual
import Mathlib.Tactic.ToExpr
import Mathlib.Tactic.ToFun
import Mathlib.Tactic.ToLevel
import Mathlib.Tactic.Trace
import Mathlib.Tactic.Translate.Attributes
import Mathlib.Tactic.Translate.Core
import Mathlib.Tactic.Translate.GuessName
import Mathlib.Tactic.Translate.Reorder
import Mathlib.Tactic.Translate.TagUnfoldBoundary
import Mathlib.Tactic.Translate.ToAdditive
import Mathlib.Tactic.Translate.ToDual
import Mathlib.Tactic.Translate.UnfoldBoundary
import Mathlib.Tactic.TryThis
import Mathlib.Tactic.TypeStar
import Mathlib.Tactic.UnsetOption
import Mathlib.Tactic.Use
import Mathlib.Tactic.Variable
import Mathlib.Tactic.WLOG
import Mathlib.Tactic.Widget.Calc
import Mathlib.Tactic.Widget.CongrM
import Mathlib.Tactic.Widget.Conv
import Mathlib.Tactic.Widget.LibraryRewrite
import Mathlib.Tactic.Widget.SelectInsertParamsClass
import Mathlib.Tactic.Widget.SelectPanelUtils
import Mathlib.Tactic.Zify
import Mathlib.Tactic.Have
import Mathlib.Tactic.Cases
